# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-14 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_takepayment'),
        ('ecomApp', '0002_auto_20220502_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=200, null=True)),
                ('customerGst', models.CharField(blank=True, max_length=200, null=True)),
                ('customerPhone', models.CharField(blank=True, max_length=200, null=True)),
                ('customerEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('customerAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('customerState', models.CharField(blank=True, max_length=200, null=True)),
                ('salesType', models.CharField(blank=True, default='Normal', max_length=200, null=True)),
                ('paymentType', models.CharField(blank=True, default='Cash', max_length=200, null=True)),
                ('creditDays', models.IntegerField(default=0)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceDate', models.DateField(blank=True, null=True)),
                ('subTotal', models.FloatField(default=0.0)),
                ('taxable', models.FloatField(default=0.0)),
                ('totalFinal', models.FloatField(default=0.0)),
                ('billDisc', models.FloatField(default=0.0)),
                ('gst', models.FloatField(default=0.0)),
                ('grandTotal', models.FloatField(default=0.0)),
                ('roundOff', models.FloatField(default=0.0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('paidDate', models.DateField(blank=True, null=True)),
                ('chequeDetail', models.CharField(blank=True, max_length=500, null=True)),
                ('deliveryNote', models.CharField(blank=True, max_length=500, null=True)),
                ('supplierReference', models.CharField(blank=True, max_length=500, null=True)),
                ('buyersOrderNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('dispatchDocumentNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('dispatchThrough', models.CharField(blank=True, max_length=500, null=True)),
                ('otherReference', models.CharField(blank=True, max_length=500, null=True)),
                ('dispatchNoteDate', models.CharField(blank=True, max_length=500, null=True)),
                ('destination', models.CharField(blank=True, max_length=500, null=True)),
                ('otherCharges', models.FloatField(default=0.0)),
                ('paidAmount', models.FloatField(default=0.0)),
                ('dueOrReturnAmount', models.FloatField(default=0.0)),
                ('invoiceActualNumber', models.IntegerField(default=0)),
                ('paidAgainstBill', models.FloatField(default=0.0)),
                ('personalDiscount', models.FloatField(default=0.0)),
                ('expectedDeliveryDate', models.DateField(blank=True, null=True)),
                ('addedByUser', models.CharField(blank=True, max_length=100, null=True)),
                ('isSold', models.BooleanField(default=False)),
                ('confirmBookID', models.CharField(blank=True, max_length=100, null=True)),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CompanyProfile')),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('invoiceSeriesID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Invoice')),
            ],
            options={
                'verbose_name_plural': 'c) Booking List',
            },
        ),
        migrations.CreateModel(
            name='BookingProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('gst', models.FloatField(default=0.0)),
                ('disc', models.FloatField(default=0.0)),
                ('netRate', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('margin', models.FloatField(default=1.0)),
                ('batchID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ProductBatch')),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('salesID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomApp.BookingEcom')),
            ],
        ),
    ]
