# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_salesreturn_salesreturnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslaterproduct',
            name='margin',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='margin',
            field=models.FloatField(default=1.0),
        ),
    ]
